[package]
name = "a8-bot"
version = "0.0.1"
edition = "2021"

[dependencies]
solana-client = "2.1.13"
solana-sdk = "2.1.13"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"
log = "0.4"
env_logger = "0.11.6"